### ISSUE TITLE
KeyError: 'upload_id'

### ISSUE THREAD

**Issue by ghost** [softcoder24/instagram-share-post#4]
Traceback (most recent call last):
  File "share.py", line 13, in <module>
    share_post = insta.post(image, caption="Lovely City")
  File "/home/pc/instagramBot/shudleApp/insta_session/insta_share/insta_share/instagram.py", line 88, in post
    upload_id = Instagram.upload_photo(self, photo)
  File "/home/pc/instagramBot/shudleApp/insta_session/insta_share/insta_share/instagram.py", line 79, in upload_photo
    upload_id = json_data['upload_id']
KeyError: 'upload_id'
I didn`t manage to install jsonlib but I have build in json in python or that is different

**Comment by oluca** [comment]
Can you share your code?
